### PR TITLE
Fix copyright date

### LINKED ISSUE #478: Remove date from copyright
## Description

The date in the footer is out of date. 

We should remove it so that we don't have to keep updating it.

## Step to reproduce

1. Go to the home page
2. Observer last year's date in the footer

### PR DESCRIPTION
**Pull request by Aditya-Kolla**
I've changed the component so that it must be able to display the current year on its own.

Closes #478

### CODE REVIEW

**Comment by jeddy3** [comment]
Our CI (circleCI.com) doesn't appear to be active for forks. I've created a bug issue for it (https://github.com/barnardos/design-system/issues/486), which I'll work on soon.

**Comment by Aditya-Kolla** [comment]
@jeddy3 You're welcome :)

**Comment by jeddy3** [comment]
@Aditya-Kolla Thanks again for the PR. We've now enabled CircleCI for forks. Can you please remove your changes to `package.json` in your branch and push up a commit. That should resolve the conflict and trigger a build on our CircleCI. We'll then be able to merge this PR.

**Comment by Aditya-Kolla** [comment]
Lemme just redo the PR. I messed up a bit. Closing this PR for now.

**Comment by jeddy3** [comment]
> Lemme just redo the PR. I messed up a bit. Closing this PR for now.

No worries. Resolving conflicts and doing rebases often gets messy!

**Pull request closed without merging**
