### PR TITLE
Fix communication of layout and typography

### LINKED ISSUE #84: Fix communication of type scale
A user of the service said it would be useful to have the lower end of the type scale written out, e.g:

screen shot 2018-03-22 at 18 57 11

### PR DESCRIPTION
**Pull request by jeddy3**
Closes #84

### CODE REVIEW

**Comment by sl33p** [comment]
I'm wondering if the example labels should be to the side of the elements rather than obscuring them. Also, it's not evident where the numbers (esp 7 and 11) are derived from. Explaining how the numbers relate to the rules would really help explain the concept.

screenshot 2018-05-10 14 29 11

**Comment by jeddy3** [comment]
@sl33p Good feedback. We considered placing the scale to the side, but this presented problems on very small viewports (e.g. iPhone SE). However, we think we've developed a solution that better communicates the spacing and line height rule (over the actual example content). We also realised that there are two types of figures/examples in the design system: 'Example Implementations' and 'Figures'. Example Implementations can be used as-is, whereas Figures are primarily meant to illustrate something. As such, we've converted the spacing illustration into a Figure (e.g. grey background). 

Lastly, we also realised that the use of the teal box is now redundant. Since its inception, we've developed a language (e.g "you should" vs "you could") across the other pages to distinguish between "rules" and "suggestions". Using the teal box isn't sustainable as "you should"s are peppered throughout the design system. So, we brought the layout and typography page inline with the other pages.

**Comment by sl33p** [comment]
The advantage of the previous layout of the example was that it was clear that the coloured labels were on overlay showing the scale of the elements underneath. I feel that is now lost, and it's hard to understand what the example is showing. If the main problem was small viewports I think it would be acceptable to partly obscure the elements, e.g. have the labels on the left as suggested, then as much of the elements as you can fit within the viewport. Would this work?

My previous comment about providing some further explanation of what the example means (e.g. what's 4x11?) also stands.

**Comment by sl33p** [comment]
Soz, didn't realise there'd been a revision. It's looking great, the only thing I don't get is the beige(?) area of padding(?) between the _Full name_ label and the input element. 

What is it, and why is it without a measurement?

screenshot-2018-05-16-15 26 51

**Comment by jeddy3** [comment]
We've added a measurement for the padding of 8.

**Comment by sl33p** [comment]
💯

**Pull request merged**
