### PR TITLE
Fix emphasis of rules

### LINKED ISSUE #39: Fix the emphasis of the three layout and typographic rules
While chatting with the Creative Team it became clear that there needs to be a better separation between the _rules that should be followed_ and the _suggested implementation_ of those rules. Currently, the rules aren't emphasised and their importance isn't clear.

Additionally, perhaps moving the example directly below the rules is more valuable as it can become just an example of the three rules rather than the current _mix_ of rules and suggestions? e.g.

artboard

This shows all three rules in effect: the 8px spacing, 4px line height and the 1.125 type scale.

### PR DESCRIPTION
**Pull request by kelliewellingtons**
Visually emphasises the rules, while de-emphasising the suggestions. Revisited copy to reflect thse visual changes.

Closes #39

### CODE REVIEW

**Comment by sl33p** [comment]
First impression of the border around the rules was that it's quite overpowering. I agree that the emphasis needs to be on the rules, but maybe a different treatment would reach the same goal. A coloured background with a top border might be an option?

**Comment by sl33p** [comment]
screen shot 2018-03-06 at 15 58 09

**Comment by kelliewellingtons** [comment]
@sl33p What do you think of this as a solution?
screen shot 2018-03-06 at 17 09 11

**Comment by sl33p** [comment]
Looks great, much less of the _speak to a GP if you got ebola_ which is the tone we want 🐵

**Pull request merged**
